### PR TITLE
kernel: add support for 4.14 kernel

### PR DESCRIPTION
**Pull request by dylad**
This PR should add support for AXFS on 4.14 (and above) kernel
@seebe May be interested by this PR.
I've tested this PR on a 4.15 kernel

### CODE REVIEW

**Comment by seebe** [comment]
Thank you for this patch! I confirmed it works on 4.14.

However, if you could make the changes below for me, I can accept the pull request:

ALL: Please use tabs instead of spaces

Hunk 1: 'virtual_address' was changed to just 'address' starting in 4.10. Also, it is better to keep the #ifdef code in order of kernel version.

Hunk 2: We actually want to keep the (2,6,22) before the function header line the way it is. The reason is that there is a script used to go in and strip out all the #ifdef in the code and anything in between, so we'd loose the function header. For any version before 4.14

Hunk 3: The 2nd parameter for .fault was dropped in 4.11.

Hunk 4: The 2nd parameter for .fault was dropped in 4.11.


Basically, below is what I am looking for. If you can re-submit what I have below, I can pull it directly.

---------------------
```
diff --git a/kernel/fs/axfs/axfs_inode.c b/kernel/fs/axfs/axfs_inode.c
index e5a60f6..d44d574 100644
--- a/kernel/fs/axfs/axfs_inode.c
+++ b/kernel/fs/axfs/axfs_inode.c
@@ -589,8 +589,10 @@ static int do_dax_noblk_fault(struct vm_area_struct *vma, struct vm_fault *vmf,
 
 #if LINUX_VERSION_CODE < KERNEL_VERSION(4,5,0)
        error = vm_insert_mixed(vma, (unsigned long)vmf->virtual_address, pfn);
-#else
+#elif LINUX_VERSION_CODE < KERNEL_VERSION(4,10,0)
        error = vm_insert_mixed(vma, (unsigned long)vmf->virtual_address, __pfn_to_pfn_t(pfn, PFN_DEV));
+#else
+       error = vm_insert_mixed(vma, (unsigned long)vmf->address, __pfn_to_pfn_t(pfn, PFN_DEV));
 #endif
 
        i_mmap_unlock_read(mapping);
@@ -646,12 +648,19 @@ int xip_file_fault(struct vm_area_struct *vma, struct vm_fault *vmf)
  *    0 or error number
  *
  *****************************************************************************/
+#if LINUX_VERSION_CODE < KERNEL_VERSION(4,11,0)
 static int axfs_fault(struct vm_area_struct *vma, struct vm_fault *vmf)
 #else
+static int axfs_fault(struct vm_fault *vmf)
+#endif
+#else
 static struct page *axfs_nopage(struct vm_area_struct *vma,
                                unsigned long address, int *type)
 #endif
 {
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(4,11,0)
+       struct vm_area_struct *vma = vmf->vma;
+#endif
        struct file *file = vma->vm_file;
 #if LINUX_VERSION_CODE > KERNEL_VERSION(3,10,0)
        struct inode *inode = file_inode(file);
@@ -701,7 +710,9 @@ static struct page *axfs_nopage(struct vm_area_struct *vma,
                return xip_file_nopage(vma, address, type);
 #endif
 #endif
-#if LINUX_VERSION_CODE > KERNEL_VERSION(2,6,22)
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(4,11,0)
+       return filemap_fault(vmf);
+#elif LINUX_VERSION_CODE > KERNEL_VERSION(2,6,22)
        return filemap_fault(vma, vmf);
 #else
        return filemap_nopage(vma, address, type);
```

**Comment by dylad** [comment]
Thanks for the review !
I think I've addressed all your comments.
I'll squash if you're OK with the new changes.

**Comment by seebe** [comment]
Yes, that looks good. Thanks!

If you can squash it back to 1 commit, I'll go ahead and pull it.

**Comment by dylad** [comment]
Done.

**Comment by seebe** [comment]
Merged.
Thanks!

**Comment by dylad** [comment]
Thanks @seebe :)

**Pull request merged**
